version: "3.8"

services:
  app:
    build: .
    container_name: evangeliontestmode01
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${mysql://vq87a2wc0jge3nyt:hidw10hcb40ds5km@nnmeqdrilkem9ked.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/kkjc39umeunk66pp}
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
