version: "3.8"

services:
  app:
    image: python:3.11
    build: .
    container_name: evangeliontestmode01
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SLACK_BOT_TOKEN=xoxb-8636273291735-8678751508816-hPc58D8WQC0efs2HjP5t8khz
      - SLACK_APP_TOKEN=xapp-1-A08KDE065DH-8707428627120-216bc6c811899046db3e7c1a2451808d44a79651bbb408401698ec4773c50dfa
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
